# Play tennies prediction using Decision tree 

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import matplotlib.pyplot as plt


In [27]:
# -----------------------------
# 1. Load the dataset
# -----------------------------

df = pd.read_csv("C:/Users/LENOVO P14S/AIML/ALL DATA SETS/Play Tennis.csv")
df.head()

Day   Outlook Temprature Humidity    Wind Play_Tennis
0  D1     Sunny        Hot     High    Weak          No
1  D2     Sunny        Hot     High  Strong          No
2  D3  Overcast        Hot     High    Weak         Yes
3  D4      Rain       Mild     High    Weak         Yes
4  D5      Rain       Cool   Normal    Weak         Yes

In [28]:
# -----------------------------
# 2. Preprocessing
# -----------------------------
X = df.drop(columns=['Day','Play_Tennis'])
y = df['Play_Tennis']

In [29]:
# Convert categorical features into numeric (One-Hot Encoding)
X = pd.get_dummies(X)

# Encode target variable
le = LabelEncoder()
y = le.fit_transform(y)   # Yes=1, No=0


In [30]:
X.head()

Outlook_Overcast  Outlook_Rain  Outlook_Sunny  Temprature_Cool  \
0             False         False           True            False   
1             False         False           True            False   
2              True         False          False            False   
3             False          True          False            False   
4             False          True          False             True   

   Temprature_Hot  Temprature_Mild  Humidity_High  Humidity_Normal  \
0            True            False           True            False   
1            True            False           True            False   
2            True            False           True            False   
3           False             True           True            False   
4           False            False          False             True   

   Wind_Strong  Wind_Weak  
0        False       True  
1         True      False  
2        False       True  
3        False       True  
4        False       True

In [31]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [32]:

# Train-Test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)



In [33]:
# -----------------------------
# 3. Decision Tree
# -----------------------------
dtc = DecisionTreeClassifier(criterion="entropy", random_state=42)
dtc.fit(X_train, y_train)
y_pred_dt = dtc.predict(X_test)

print("Decision Tree Accuracy:", metrics.accuracy_score(y_test, y_pred_dt))

Decision Tree Accuracy: 0.4


In [34]:
# Plot tree only for reference, not mandatory
#plt.figure(figsize=(12,8))
#plot_tree(dtc, feature_names=X.columns, class_names=le.classes_, filled=True)
#plt.show()

In [35]:
# -----------------------------
# 4. Random Forest
# -----------------------------
rfc = RandomForestClassifier(n_estimators=10, criterion="entropy", random_state=42)
rfc.fit(X_train, y_train)
y_pred_rf = rfc.predict(X_test)

print("Random Forest Accuracy:", metrics.accuracy_score(y_test, y_pred_rf))


Random Forest Accuracy: 0.4


# Breast cancer prediction using Decision tree

In [36]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_breast_cancer

In [37]:

cancer_data = load_breast_cancer()

In [38]:
type(cancer_data)  # Note:since we are not using pandas to read data , "cancer_data" is not a dataframe

sklearn.utils._bunch.Bunch

In [39]:
list(cancer_data.target_names)

[np.str_('malignant'), np.str_('benign')]

In [16]:
cancer_data.feature_names # Study about cancer data in Kaggle or UCI website

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [17]:
# convert the data to dataframe 
cancer_df = pd.DataFrame(cancer_data.data, columns=cancer_data.feature_names)
cancer_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(cancer_df, 
                                                    cancer_data.target, 
                                                    test_size = 0.33, 
                                                    random_state = 42)

In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

In [20]:
# Create Decision Tree classifer object
dtc = DecisionTreeClassifier()

# Train Decision Tree Classifer
model = dtc.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

In [21]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9361702127659575


In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 64,   3],
       [  9, 112]])

In [ ]:
# You can also plot confusion matrix 
import matplotlib.pyplot as plt
from sklearn.metrics import plot_confusion_matrix
 
matrix = plot_confusion_matrix(model, X_test, y_test, cmap=plt.cm.Reds)


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

#  Using Random forest classifier for comparision 

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(cancer_df, 
                                                    cancer_data.target, 
                                                    test_size = 0.33, 
                                                    random_state = 42)

In [25]:
from sklearn.ensemble import RandomForestClassifier  
forest = RandomForestClassifier(n_estimators=100,random_state=0)
forest.fit(X_train,y_train)

#you can tune parameter such as:
# - n_job (how many cores)(n_job=-1 => all cores)
# - max_depth
# - max_feature


# If you want you can check acc for training datra also
#print('acc for training data: {:.3f}'.format(forest.score(X_train,y_train))) 

#Predict the response for test dataset
y_pred = forest.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))



Accuracy: 0.9521276595744681


In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 61,   6],
       [  3, 118]])

In [26]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.91      0.93        67
           1       0.95      0.98      0.96       121

    accuracy                           0.95       188
   macro avg       0.95      0.94      0.95       188
weighted avg       0.95      0.95      0.95       188

